osx_image: xcode7.2
language: objective-c
matrix:
  include:
    - osx_image: xcode7.2
      env: SCHEME="ObjectiveGit Mac"
    - osx_image: xcode7.2
      env: SCHEME="ObjectiveGit iOS"
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
install: script/bootstrap
script: script/cibuild
notifications:
  email: false
